def distinct_powers(a_limit, b_limit):
    terms = set()
    for a in range(2, a_limit + 1):
        for b in range(2, b_limit + 1):
            terms.add(a ** b)
    return len(terms)

if __name__ == "__main__":
    a_limit = 100
    b_limit = 100
    result = distinct_powers(a_limit, b_limit)
    print(f"The number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ {a_limit} and 2 ≤ b ≤ {b_limit} is {result}")